services:
  stable_diffusion_docker:
    build: .
    env_file:
      - .env
    volumes:
      - ${DOCKER_CACHE_DIR}:/root/.cache
    command: [ "sleep", "infinity" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
